# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: react-client-master CI and CD

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2 
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: add npm dependency, run test with coverage, build and deploy   
      run: npm install
    - name: npm test with coverage, npm build     
      run: npm test -- --coverage
    - name: npm build     
      run: npm run build
    - name: deploy to github pages
      run: |
        git config user.name Rajkumar M
        git config user.email igilli.2007@gmail.com
        git remote set-url origin https://github.com/rajkumarmg/react-client.git
        npm run deploy
      env:
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        github_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        repository: ${{ github.repository }}  
